# Generated by Django 3.1.3 on 2020-12-31 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_message_reply_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='viewed_by_recipient',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='message_reply',
            name='message',
            field=models.TextField(max_length=40000000),
        ),
    ]
