# Generated by Django 3.1.3 on 2020-12-31 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201231_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='new_reply_from_recipient',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='new_reply_from_sender',
            field=models.BooleanField(default=False),
        ),
    ]
