# Generated by Django 3.1.3 on 2020-12-31 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20201231_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='last_updated',
            field=models.DateTimeField(null=True),
        ),
    ]
