# Generated by Django 3.1.3 on 2021-01-02 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0007_auto_20210101_2128'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biography', models.CharField(max_length=10000000, null=True)),
                ('dorm', models.CharField(max_length=10000000, null=True)),
                ('year', models.CharField(max_length=6, null=True)),
                ('phone_number', models.CharField(max_length=14, null=True)),
                ('contact_email', models.CharField(default='', max_length=10000000, null=True)),
                ('first_name', models.CharField(max_length=100000000, null=True)),
                ('last_name', models.CharField(max_length=100000000, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
