# Generated by Django 3.1.3 on 2021-01-04 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='year',
        ),
        migrations.AddField(
            model_name='user_profile',
            name='is_initially_setup',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='biography',
            field=models.CharField(default='', max_length=10000000, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='dorm',
            field=models.CharField(default='', max_length=10000000, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='first_name',
            field=models.CharField(default='', max_length=100000000, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='last_name',
            field=models.CharField(default='', max_length=100000000, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='phone_number',
            field=models.CharField(default='', max_length=14, null=True),
        ),
    ]
