# Generated by Django 3.1.3 on 2021-01-04 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210104_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='is_initially_setup',
        ),
    ]
