# Generated by Django 3.1.3 on 2021-01-22 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(max_length=4)),
                ('courseNumber', models.CharField(max_length=10)),
                ('courseName', models.CharField(blank=True, default='No name given', max_length=200)),
                ('professor', models.CharField(blank=True, default='No professor given', max_length=500)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('location', models.CharField(blank=True, default='', max_length=20000)),
                ('views', models.PositiveIntegerField(default=0)),
                ('numMembers', models.PositiveIntegerField(default=1)),
                ('onMonday', models.BooleanField(default=False)),
                ('onTuesday', models.BooleanField(default=False)),
                ('onWednesday', models.BooleanField(default=False)),
                ('onThursday', models.BooleanField(default=False)),
                ('onFriday', models.BooleanField(default=False)),
                ('members', models.ManyToManyField(related_name='classes_is_following', to=settings.AUTH_USER_MODEL)),
                ('starter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Meetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=20000)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('location', models.CharField(blank=True, default='', max_length=20000)),
                ('onMonday', models.BooleanField(default=False)),
                ('onTuesday', models.BooleanField(default=False)),
                ('onWednesday', models.BooleanField(default=False)),
                ('onThursday', models.BooleanField(default=False)),
                ('onFriday', models.BooleanField(default=False)),
                ('onSaturday', models.BooleanField(default=False)),
                ('onSunday', models.BooleanField(default=False)),
                ('views', models.PositiveIntegerField(default=1)),
                ('maxCapacity', models.PositiveIntegerField(default=10)),
                ('members', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('starter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='MeetupConversationTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=20000)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('meetupReference', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='meetup_topics', to='cal.meetup')),
                ('starter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetup_topics_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_updated'],
            },
        ),
        migrations.CreateModel(
            name='MeetupConversationPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=4000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_meetup_posts', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetup_topic_posts', to='cal.meetupconversationtopic')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='MeetupConversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=20000)),
                ('meetupReference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetup_conversation', to='cal.meetup')),
            ],
        ),
        migrations.CreateModel(
            name='ClassConversationTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, default='No description provided', max_length=20000)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('classReference', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='class_topics', to='cal.class')),
                ('starter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_topics_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['last_updated'],
            },
        ),
        migrations.CreateModel(
            name='ClassConversationPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=4000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_class_posts', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_topic_posts', to='cal.classconversationtopic')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassConversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('classReference', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='cal.class')),
            ],
        ),
    ]
