# Generated by Django 3.1.3 on 2020-12-15 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0002_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='courseNumber',
            field=models.CharField(max_length=10),
        ),
    ]
