# Generated by Django 3.1.3 on 2020-12-15 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0004_auto_20201215_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='onFriday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meetup',
            name='onMonday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meetup',
            name='onThursday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meetup',
            name='onTuesday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meetup',
            name='onWednesday',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='meetup',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='meetup',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
