# Generated by Django 3.1.3 on 2020-12-16 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0005_auto_20201215_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='location',
            field=models.CharField(blank=True, default='', max_length=20000),
        ),
        migrations.AddField(
            model_name='meetup',
            name='location',
            field=models.CharField(blank=True, default='', max_length=20000),
        ),
        migrations.AlterField(
            model_name='meetup',
            name='title',
            field=models.CharField(max_length=15),
        ),
    ]
