# Generated by Django 3.1.3 on 2020-12-16 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0006_auto_20201216_0213'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
