# Generated by Django 3.1.3 on 2020-12-16 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0007_class_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='members',
            field=models.CharField(blank=True, default='', max_length=1000000000000000000000000000000000),
        ),
        migrations.AddField(
            model_name='meetup',
            name='members',
            field=models.CharField(blank=True, default='', max_length=1000000000000000000000000000000000),
        ),
    ]
