# Generated by Django 3.1.3 on 2020-12-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0008_auto_20201216_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='numMembers',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
