# Generated by Django 3.1.3 on 2020-12-16 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0009_class_nummembers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='members',
        ),
        migrations.RemoveField(
            model_name='meetup',
            name='members',
        ),
    ]
