# Generated by Django 3.1.3 on 2020-12-16 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0010_auto_20201216_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='numMembers',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
