# Generated by Django 3.1.3 on 2020-12-16 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0011_auto_20201216_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='professor',
            field=models.CharField(blank='No professor given', max_length=500),
        ),
    ]
