# Generated by Django 3.1.3 on 2020-12-16 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0013_auto_20201216_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='professor',
            field=models.CharField(default='No professor given', max_length=500),
        ),
    ]
