# Generated by Django 3.1.3 on 2020-12-16 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0016_classconversation_classconversationpost_classconversationtopic'),
    ]

    operations = [
        migrations.AddField(
            model_name='classconversation',
            name='classReference',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='class_conversation', to='cal.class'),
        ),
    ]
