# Generated by Django 3.1.3 on 2020-12-17 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0017_classconversation_classreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classconversation',
            name='classReference',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='cal.class'),
        ),
    ]
