# Generated by Django 3.1.3 on 2020-12-17 23:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cal', '0018_auto_20201217_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classconversationtopic',
            name='starter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_topics_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
