# Generated by Django 3.1.3 on 2020-12-17 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0019_auto_20201217_2301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classconversationtopic',
            old_name='ClassConversation',
            new_name='conversation',
        ),
    ]
