# Generated by Django 3.1.3 on 2020-12-18 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0020_auto_20201217_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classconversationtopic',
            name='conversation',
        ),
        migrations.AddField(
            model_name='classconversationtopic',
            name='classReference',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='class_topics', to='cal.class'),
        ),
        migrations.AddField(
            model_name='classconversationtopic',
            name='description',
            field=models.CharField(blank=True, default='No description provided', max_length=20000),
        ),
    ]
