# Generated by Django 3.1.3 on 2020-12-18 23:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cal', '0021_auto_20201218_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='onSaturday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meetup',
            name='onSunday',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='meetup',
            name='description',
            field=models.CharField(max_length=20000),
        ),
        migrations.AlterField(
            model_name='meetup',
            name='title',
            field=models.CharField(max_length=25),
        ),
        migrations.CreateModel(
            name='MeetupConversationTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=20000)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('meetupReference', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='meetup_topics', to='cal.meetup')),
                ('starter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetup_topics_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MeetupConversationPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=4000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_meetup_posts', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetup_topic_posts', to='cal.meetupconversationtopic')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MeetupConversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=20000)),
                ('meetupReference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetup_conversation', to='cal.meetup')),
            ],
        ),
    ]
