# Generated by Django 3.1.3 on 2020-12-19 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0022_auto_20201218_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='views',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
