# Generated by Django 3.1.3 on 2020-12-23 21:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cal', '0023_meetup_views'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classconversationpost',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='classconversationtopic',
            options={'ordering': ['-last_updated']},
        ),
        migrations.AlterModelOptions(
            name='meetup',
            options={'ordering': ['-start_time']},
        ),
        migrations.AlterModelOptions(
            name='meetupconversationpost',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='meetupconversationtopic',
            options={'ordering': ['-last_updated']},
        ),
        migrations.AddField(
            model_name='meetup',
            name='maxCapacity',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='meetup',
            name='members',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
