# Generated by Django 3.1.3 on 2020-12-24 19:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cal', '0024_auto_20201223_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='maxCapacity',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='class',
            name='members',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
