# Generated by Django 3.1.3 on 2020-12-24 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0025_auto_20201224_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='maxCapacity',
        ),
    ]
