# Generated by Django 3.1.3 on 2021-01-01 17:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cal', '0026_remove_class_maxcapacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='members',
            field=models.ManyToManyField(related_name='classes_is_following', to=settings.AUTH_USER_MODEL),
        ),
    ]
