# Generated by Django 3.1.3 on 2021-01-02 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0027_auto_20210101_1248'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classconversationtopic',
            options={'ordering': ['last_updated']},
        ),
    ]
