# Generated by Django 3.1.3 on 2020-12-24 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cal', '0026_remove_class_maxcapacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='class_wiki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(max_length=4)),
                ('courseNumber', models.CharField(max_length=10)),
                ('courseName', models.CharField(blank=True, default='No name given', max_length=200)),
                ('professor', models.CharField(blank=True, default='No professor given', max_length=500)),
                ('views', models.PositiveIntegerField(default=0)),
                ('contributors', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('current_connected_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wiki', to='cal.class')),
                ('starter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_wikis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-views'],
            },
        ),
        migrations.CreateModel(
            name='class_wiki_topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=500)),
                ('description', models.CharField(blank=True, default='No description provided', max_length=20000)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('class_wiki_reference', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='class_wiki_topics', to='classwiki.class_wiki')),
                ('starter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_wiki_topics_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_updated'],
            },
        ),
        migrations.CreateModel(
            name='class_wiki_conversation_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=4000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_class_wiki_posts', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_wiki_topic_posts', to='classwiki.class_wiki_topic')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
