# Generated by Django 3.1.3 on 2021-01-22 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='class_wiki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(max_length=4, verbose_name='Department')),
                ('courseNumber', models.CharField(max_length=10, verbose_name='Course Number')),
                ('courseName', models.CharField(blank=True, default='No name given', max_length=200, verbose_name='Course Name')),
                ('professor', models.CharField(blank=True, default='No professor given', max_length=500, verbose_name='Professor')),
                ('views', models.PositiveIntegerField(default=0)),
                ('is_reported_duplicate', models.BooleanField(default=False)),
                ('contributors', models.ManyToManyField(blank=True, related_name='contributing_wikis', to=settings.AUTH_USER_MODEL)),
                ('current_connected_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wiki', to='cal.class')),
                ('followers', models.ManyToManyField(blank=True, related_name='following_wikis', to=settings.AUTH_USER_MODEL)),
                ('starter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_wikis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['views'],
            },
        ),
        migrations.CreateModel(
            name='class_wiki_topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=30, null=True)),
                ('description', models.CharField(blank=True, default='No description provided', max_length=20000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now_add=True, null=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('class_wiki_reference', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_wiki_topics', to='classwiki.class_wiki')),
                ('starter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_wiki_topics_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='class_wiki_topic_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=40000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_class_wiki_posts', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_wiki_topic_posts', to='classwiki.class_wiki_topic')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='class_wiki_content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=20000)),
                ('content', models.TextField(max_length=400000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('class_wiki', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content', to='classwiki.class_wiki')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_class_wiki_content', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
