# Generated by Django 3.1.3 on 2020-12-24 22:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classwiki', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='class_wiki_conversation_post',
            new_name='class_wiki_topic_post',
        ),
    ]
