# Generated by Django 3.1.3 on 2020-12-24 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0026_remove_class_maxcapacity'),
        ('classwiki', '0002_auto_20201224_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_wiki',
            name='current_connected_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wiki', to='cal.class'),
        ),
    ]
