# Generated by Django 3.1.3 on 2020-12-24 23:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classwiki', '0003_auto_20201224_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_wiki',
            name='contributors',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
