# Generated by Django 3.1.3 on 2020-12-25 02:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classwiki', '0005_auto_20201224_1805'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class_wiki_topic',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='class_wiki_topic_post',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='class_wiki_topic',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='class_wiki_content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=20000)),
                ('content', models.TextField(max_length=400000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('class_wiki', models.ManyToManyField(related_name='content', to='classwiki.class_wiki')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_class_wiki_content', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
