# Generated by Django 3.1.3 on 2020-12-25 03:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classwiki', '0006_auto_20201224_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='class_wiki',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='following_wikis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='class_wiki',
            name='contributors',
            field=models.ManyToManyField(blank=True, related_name='contributing_wikis', to=settings.AUTH_USER_MODEL),
        ),
    ]
