# Generated by Django 3.1.3 on 2020-12-26 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classwiki', '0007_auto_20201224_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_wiki_content',
            name='subject',
            field=models.CharField(max_length=50),
        ),
    ]
