# Generated by Django 3.1.3 on 2020-12-26 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classwiki', '0008_auto_20201226_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class_wiki_content',
            name='class_wiki',
        ),
        migrations.AddField(
            model_name='class_wiki_content',
            name='class_wiki',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content', to='classwiki.class_wiki'),
        ),
    ]
