# Generated by Django 3.1.3 on 2020-12-29 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classwiki', '0009_auto_20201226_1704'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class_wiki',
            options={'ordering': ['views']},
        ),
        migrations.AlterModelOptions(
            name='class_wiki_content',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='class_wiki_topic',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='class_wiki_topic_post',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='class_wiki_topic',
            name='class_wiki_reference',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_wiki_topics', to='classwiki.class_wiki'),
        ),
        migrations.AlterField(
            model_name='class_wiki_topic',
            name='description',
            field=models.CharField(blank=True, default='No description provided', max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name='class_wiki_topic',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='class_wiki_topic',
            name='starter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_wiki_topics_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='class_wiki_topic',
            name='subject',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='class_wiki_topic_post',
            name='message',
            field=models.TextField(max_length=40000),
        ),
    ]
