# Generated by Django 3.1.3 on 2021-01-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classwiki', '0010_auto_20201229_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='class_wiki',
            name='is_duplicate',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='class_wiki',
            name='courseName',
            field=models.CharField(blank=True, default='No name given', max_length=200, verbose_name='Course Name'),
        ),
        migrations.AlterField(
            model_name='class_wiki',
            name='courseNumber',
            field=models.CharField(max_length=10, verbose_name='Course Number'),
        ),
        migrations.AlterField(
            model_name='class_wiki',
            name='dept',
            field=models.CharField(max_length=4, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='class_wiki',
            name='professor',
            field=models.CharField(blank=True, default='No professor given', max_length=500, verbose_name='Professor'),
        ),
    ]
