# Generated by Django 3.1.3 on 2021-01-13 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classwiki', '0011_auto_20210113_1013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class_wiki',
            old_name='is_duplicate',
            new_name='is_reported_duplicate',
        ),
    ]
